# Generated by Django 3.0.8 on 2020-07-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200726_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
