# Generated by Django 3.0.8 on 2020-07-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200727_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score_number',
            new_name='test_score',
        ),
    ]
